version: '3.8'  # Update the version if necessary

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: pdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Mount a volume for PostgreSQL data

  keycloak:
    image: quay.io/keycloak/keycloak:20.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/pdb
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    ports:
      - "9090:8080"
    command:
      - start-dev
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data  # Mount a volume for Keycloak data

volumes:
  postgres_data:  # Define the volume for PostgreSQL data
  keycloak_data:  # Define the volume for Keycloak data
